openapi: 3.0.0
info:
  version: 1.0.0
  title: Orders API
  description: The API for managing the orders
  contact:
    name: John Smith
    email: jsmith@company.com
servers:
  - url: http://orders.api.company.com/api/v1
paths:
  /orders:
    get:
      description: Returns all the registered orders.
      operationId: getOrders
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderWithID'
    post:
      description: Creates a new order.
      operationId: createOrder
      requestBody:
        description: Order that should be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderWithID'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /orders/{id}:
    get:
      description: Returns an order based on the provided ID
      operationId: getOrderByID
      parameters:
        - name: id
          in: path
          description: ID of the order
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderWithID'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      description: Removes the order based on the provided ID
      operationId: deleteOrder
      parameters:
        - name: id
          in: path
          description: ID of the order
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Order deleted
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      description: Updates the order based on the provided ID
      operationId: updateOrder
      requestBody:
        description: Order that should be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      parameters:
        - name: id
          in: path
          description: ID of the order
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Order updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderWithID'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    OrderWithID:
      allOf:
        - $ref: '#/components/schemas/Order'
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64

    Order:
      type: object
      required:
        - id
      properties:
        product:
          type: string
        type:
          type: string
        date:
          type: string

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
